#ifndef TOKENS_H
#define TOKENS_H

typedef enum {
    TOKEN_EOF =0,
    TOKEN_TASK, TOKEN_RUN, TOKEN_EVERY, TOKEN_DAY,
    TOKEN_AT, TOKEN_AFTER, TOKEN_IF, TOKEN_SUCCESS,
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_TIME,
    TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_ERROR
} TokenType;

#endif